// {    STUDY LOCATION OBJECT
//     id: number,
//     name: string,
//     addr: string,
//     lat: num,
//     long: num,
//     dinein: boolean,
//     indoorseats: boolean,
//     takeout: boolean,
//     noise: number / like a scale,
//     rating: number out of 5,
//     price: number on scale out of 5?,
//     wifi: boolean,
// }
const database = [
    {
        id: 1,
        name: "Starbucks",
        addr: "103 E Franklin St, Chapel Hill, NC 27514",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:true,
        indoorseats: false,
        outdoorseats: false,
        noise: 3,
        rating: 4,
        price: 4,
        wifi: true,
        des: "A Starbucks is always a good place to study. This one might be small but it;s a classic. ", 
        hashtag1: "coffee",
        hashtag2: "cornerclassic"
    },
    {
        id: 2,
        name: "Davis Library",
        addr: "208 Raleigh St, Chapel Hill, NC 27514",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:false,
        indoorseats: true,  
        outdoorseats: true,      
        noise: 3,
        rating: 5,
        price: 0,
        wifi: true,
        des: "Classic study spot with lots of variety. Limited spots so sign up online beforehand! ",
        hashtag1: "nofood",
        hashtag2: "library"
    },
    {
        id: 3,
        name: "Robert B. House Undergraduate Library",
        addr: "203 South Rd #3942, Chapel Hill, NC 27599",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:false,
        indoorseats: true,
        outdoorseats: true,
        noise: 3,
        rating: 5,
        price: 0,
        wifi: true,
        des: "Formally known as the Undergraduate Library, this is a classic place for an all-nighter. ", 
        hashtag1: "nosleep",
        hashtag2: "grindtime"
    },
    {
        id: 4,
        name: "Stone and Leaf Café ",
        addr: "207 South Rd, Chapel Hill, NC 27599",
        lat: 0,
        long: 0,
        dinein:true,
        takeout:true,
        indoorseats: true,
        outdoorseats: true,
        noise: 4,
        rating: 5,
        price: 4,
        wifi: true,
        des: "A classic place to study within the UNC Student Stores, or just grab a coffee between classes. ", 
        hashtag1: "coffee",
        hashtag2: "StudentStores"
    },
    {
        id: 5,
        name: "Fedex Center",
        addr: "301 Pittsboro Street Chapel Hill, NC 27516",
        lat: 0,
        long: 0,
        dinein:true,
        takeout:true,
        indoorseats: true,
        outdoorseats: true,
        noise: 4,
        rating: 5,
        price: 3,
        wifi: true,
        des: "This place might be a hike, but it's definitely worth it! FedEx has some great natural light and has a lot of great speakers. ", 
        hashtag1: "buisnessy",
        hashtag2: "brandnew"
    },
    {
        id: 6,
        name: "Health Science Library",
        addr: "335 S Columbia St, Chapel Hill, NC 27599",
        lat: 0,
        long: 0,
        dinein:true,
        takeout:true,
        indoorseats: true,
        outdoorseats: false,
        noise: 3,
        rating: 5,
        price: 3,
        wifi: true,
        des: "A great place to study if you're looking for some smart STEM friends! ",
        hashtag1: "medicine",
        hashtag2: "science"
    },
    {
        id: 7,
        name: "Stone Library",
        addr: "Hanes Art Center, 121 E Cameron Ave, Chapel Hill, NC 27514",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:false,
        indoorseats: true,
        outdoorseats: false,
        noise: 3,
        rating: 5,
        price: 0,
        wifi: true,
        des: "Why not study right next to the football stadium?! This is a smaller space but great for focusing. ", 
        hashtag1: "centralcampus",
        hashtag2: "focus"
    },
    {
        id: 8,
        name: "Chapel Hill Public library",
        addr: "Chapel Hill Public Library, 100 Library Dr, Chapel Hill, NC 27514",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:false,
        indoorseats: false,
        outdoorseats: false,
        noise: 2,
        rating: 4,
        price: 0,
        wifi: true,
        des: "This may be a bit of a drive but what is more perfect than a public library. Patrons young and old studying here! ", 
        hashtag1: "publiclibrary",
        hashtag2: "read"
    },
    {
        id: 9,
        name: "Summit Franklin",
        addr: "140 W Franklin St, Chapel Hill, NC 27516",
        lat: 0,
        long: 0,
        dinein:true,
        takeout:true,
        indoorseats: true,
        outdoorseats: true,
        noise: 3,
        rating: 4,
        price: 5,
        wifi: true,
        des: "New coffee shop on Franklin! Very cute and yummy coffee. Bustling so not great for quiet studying. ", 
        hashtag1: "coffee",
        hashtag2: "FranklinSt"
    },
    {
        id: 10,
        name: "The Honeysuckle Cafe and Bar",
        addr: "601 W Main St, Carrboro, NC 27510",
        lat: 0,
        long: 0,
        dinein:true,
        takeout:true,
        indoorseats: true,
        outdoorseats: true,
        noise: 3,
        rating: 4,
        price: 4,
        wifi: true,
        des: "This is also a drive, but Honeysuckle has a great atmosphere for studying. Go with friends! ", 
        hashtag1: "atmosphere",
        hashtag2: "friends"
    },
    {
        id: 11,
        name: "Coco Bean Coffe Shop",
        addr: "1114 Environ Way, Chapel Hill, NC 27517",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:true,
        indoorseats: false,
        outdoorseats: true,
        noise: 3,
        rating: 4,
        price: 4,
        wifi: true,
        des: "IDK about this so place so TO DO . ", 
        hashtag1: "coffee",
        hashtag2: "study"
    },
    {
        id: 11,
        name: "Johny's Gone Fishing",
        addr: "901 W Main St, Carrboro, NC 27510",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:true,
        indoorseats: false,
        outdoorseats: true,
        noise: 3,
        rating: 4,
        price: 4,
        wifi: true,
        des: "IDK about this so place so TO DO . ", 
        hashtag1: "coffee",
        hashtag2: "study"
    },
    {
        id: 12,
        name: "Cafe Driade",
        addr: " 1215-A, E Franklin St, Chapel Hill, NC 27514",
        lat: 0,
        long: 0,
        dinein:false,
        takeout:true,
        indoorseats: false,
        outdoorseats: true,
        noise: 3,
        rating: 4,
        price: 4,
        wifi: true,
        des: "When you want to study in the middle of the trees and nature, come here! Perfect for a mild fall day . ", 
        hashtag1: "nature",
        hashtag2: "peaceful"
    },
    {
        id: 13,
        name: "Epilogue Books Chocolate Brews",
        addr: "109 E Franklin St #100, Chapel Hill, NC 27514",
        lat: 0,
        long: 0,
        dinein:true,
        takeout:true,
        indoorseats: true,
        outdoorseats: true,
        noise: 3,
        rating: 4,
        price: 4,
        wifi: true,
        des: "A combination of a bookstore and a coffee shop? Sign me up! Get a good book and a good cup of joe here! ", 
        hashtag1: "books",
        hashtag2: "cupofjoe"
    }
];
